name: Microservices CI/CD

on:
  push:
    branches:
      - main

jobs:

  user-service:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

      - uses: actions/checkout@v4

      - name: Login GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Test User Service
        working-directory: user-service
        run: ./mvnw test

      - name: Build User Image
        run: |
          docker build \
          -t ghcr.io/${{ github.repository_owner }}/user-service:latest \
          ./user-service

      - name: Push User Image
        run: |
          docker push \
          ghcr.io/${{ github.repository_owner }}/user-service:latest

  order-service:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

      - uses: actions/checkout@v4

      - name: Login GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Test Order Service
        working-directory: order-service
        run: ./mvnw test

      - name: Build Order Image
        run: |
          docker build \
          -t ghcr.io/${{ github.repository_owner }}/order-service:latest \
          ./order-service

      - name: Push Order Image
        run: |
          docker push \
          ghcr.io/${{ github.repository_owner }}/order-service:latest

  payment-service:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

      - uses: actions/checkout@v4

      - name: Login GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Test Payment Service
        working-directory: payment-service
        run: ./mvnw test

      - name: Build Payment Image
        run: |
          docker build \
          -t ghcr.io/${{ github.repository_owner }}/payment-service:latest \
          ./payment-service

      - name: Push Payment Image
        run: |
          docker push \
          ghcr.io/${{ github.repository_owner }}/payment-service:latest